version: '3'
services:
    laravel-app:
        build:
            context: .
            dockerfile: .docker/Dockerfile
        image: laravel-docker
        container_name: laravel-app
        volumes:
            - $PWD:/var/www/laravel-app
        ports:
            - 8080:80
